"""Configuration: paths derived from package location, plus domain constants.

v2 layout (this file matches v2's directory structure):
    RailRL_v2/
    ├── data/
    │   ├── raw/         ← TD_data.csv, Movements.csv, route_to_tc_all.csv
    │   ├── reference/   ← Derby_info.csv, derby_info_mapping.csv,
    │   │                  platform_*.csv, TRT1.DY2_2.SOP, derby_all.png
    │   └── domain/      ← Training_Plan_2022.docx, *.pdf (reference only)
    ├── outputs/         ← flat (no p2_data_eng wrapper):
    │   ├── inventory/
    │   ├── decisions/
    │   ├── infrastructure/
    │   ├── static_graph/
    │   ├── event_stream/
    │   ├── rewards/
    │   ├── analyses/
    │   ├── cache/
    │   ├── passes/        (new in v2, materialized per spec 01 §17.2)
    │   ├── decision_points/  (new in v2, per spec 02)
    │   └── snapshots/        (new in v2, per spec 02)
    └── src/railrl/
"""
from __future__ import annotations
import os
from pathlib import Path

# === Project paths derived from this file's location ===
_PKG_DIR     = Path(__file__).resolve().parent
_SRC_DIR     = _PKG_DIR.parent
PROJECT_ROOT = _SRC_DIR.parent

# === Input data root (raw CSVs) ===
# v2 layout: PROJECT_ROOT/data/raw/ holds TD_data.csv etc.
# Override with env var RAILRL_DATA_DIR (e.g. for shared/external mounts).

def _resolve_data_dir() -> Path:
    """Find DATA_DIR (location of TD_data.csv). v2 preference order:
       1. RAILRL_DATA_DIR env var (explicit override)
       2. PROJECT_ROOT/data/raw/  (v2 canonical layout)
       3. PROJECT_ROOT/data/       (intermediate v2-prep layouts)
       4. PROJECT_ROOT             (very flat layout)
       5. PROJECT_ROOT.parent      (v1 legacy layout)
       Fail loudly if none match.
    """
    env = os.environ.get("RAILRL_DATA_DIR")
    if env:
        return Path(env).expanduser().resolve()
    candidates = [
        PROJECT_ROOT / "data" / "raw",
        PROJECT_ROOT / "data",
        PROJECT_ROOT,
        PROJECT_ROOT.parent,
    ]
    for c in candidates:
        if (c / "TD_data.csv").exists():
            return c
    # Fallback: assume canonical v2 location even if file missing yet
    return PROJECT_ROOT / "data" / "raw"


DATA_DIR = _resolve_data_dir()

# Raw inputs (read-only)
TD_CSV          = DATA_DIR / "TD_data.csv"
MOVEMENTS_CSV   = DATA_DIR / "Movements.csv"
ROUTE_TO_TC_CSV = DATA_DIR / "route_to_tc_all.csv"

# === Static reference data (small CSVs + SOP + panel image) ===
# v2 layout: PROJECT_ROOT/data/reference/
def _resolve_reference_dir() -> Path:
    env = os.environ.get("RAILRL_REFERENCE_DIR")
    if env:
        return Path(env).expanduser().resolve()
    candidates = [
        PROJECT_ROOT / "data" / "reference",
        PROJECT_ROOT / "data",
        PROJECT_ROOT / "railrl" / "data",  # v1 legacy path
    ]
    for c in candidates:
        if (c / "Derby_info.csv").exists():
            return c
    return PROJECT_ROOT / "data" / "reference"


REFERENCE_DIR = _resolve_reference_dir()
# Back-compat alias (v1 used PROJECT_DATA_DIR)
PROJECT_DATA_DIR = REFERENCE_DIR

PLATFORM_END_SIGNALS_CSV = REFERENCE_DIR / "platform_end_signals.csv"
PLATFORM_TC_MAP_CSV      = REFERENCE_DIR / "platform_tc_map.csv"
SOP_FILE                 = REFERENCE_DIR / "TRT1.DY2_2.SOP"
DERBY_INFO_CSV           = REFERENCE_DIR / "Derby_info.csv"
DERBY_INFO_MAPPING_CSV   = REFERENCE_DIR / "derby_info_mapping.csv"
DERBY_PANEL_PNG          = REFERENCE_DIR / "derby_all.png"

# === Domain documents (PDFs, Training Plan) ===
DOMAIN_DIR = PROJECT_ROOT / "data" / "domain"
TRAINING_PLAN_DOCX  = DOMAIN_DIR / "Training_Plan_2022.docx"
HEADCODE_PDF        = DOMAIN_DIR / "headcode.pdf"
SCLASS_PDF          = DOMAIN_DIR / "S-class.pdf"
SIGNAL_NAMING_PDF   = DOMAIN_DIR / "Signalling_Nomenclature.pdf"

# === Outputs (writable, flat layout in v2) ===
OUTPUTS_DIR = Path(os.environ.get("RAILRL_OUTPUTS_DIR", PROJECT_ROOT / "outputs"))
OUTPUTS_DIR.mkdir(parents=True, exist_ok=True)

# Existing v2 output subdirs (already populated, copied from v1 P2.1-P2.4)
INVENTORY_DIR      = OUTPUTS_DIR / "inventory"
DECISIONS_DIR      = OUTPUTS_DIR / "decisions"
INFRASTRUCTURE_DIR = OUTPUTS_DIR / "infrastructure"
STATIC_GRAPH_DIR   = OUTPUTS_DIR / "static_graph"
EVENT_STREAM_DIR   = OUTPUTS_DIR / "event_stream"
REWARDS_DIR        = OUTPUTS_DIR / "rewards"
ANALYSES_DIR       = OUTPUTS_DIR / "analyses"
CACHE_DIR          = OUTPUTS_DIR / "cache"

# New v2 output subdirs (to be generated by spec 02 + later stages)
PASSES_DIR          = OUTPUTS_DIR / "passes"          # per spec 01 §17.2
DECISION_POINTS_DIR = OUTPUTS_DIR / "decision_points" # per spec 02
SNAPSHOTS_DIR       = OUTPUTS_DIR / "snapshots"       # per spec 02
TRAIN_DIR           = OUTPUTS_DIR / "train"           # per spec 04
EVAL_DIR            = OUTPUTS_DIR / "eval"            # per spec 05
XAI_DIR             = OUTPUTS_DIR / "xai"             # per spec 05
SIMULATOR_DIR       = OUTPUTS_DIR / "simulator"       # per spec 05 §14
RULE_BASE_DIR       = OUTPUTS_DIR / "rule_base"       # per spec 05 §13

# Auto-create all output subdirs (idempotent)
for _d in (INVENTORY_DIR, DECISIONS_DIR, INFRASTRUCTURE_DIR, STATIC_GRAPH_DIR,
           EVENT_STREAM_DIR, REWARDS_DIR, ANALYSES_DIR, CACHE_DIR,
           PASSES_DIR, DECISION_POINTS_DIR, SNAPSHOTS_DIR,
           TRAIN_DIR, EVAL_DIR, XAI_DIR, SIMULATOR_DIR, RULE_BASE_DIR):
    _d.mkdir(parents=True, exist_ok=True)

# === Per-stage parquet/JSON paths ===

# Stage 1 — Inventory
INVENTORY_TD_JSON         = INVENTORY_DIR / "td_inventory.json"
INVENTORY_MOVEMENTS_JSON  = INVENTORY_DIR / "movements_inventory.json"

# Stage 2 — Decision events (PR extraction)
DECISION_EVENTS_PARQUET   = DECISIONS_DIR / "decision_events.parquet"
DECISION_EVENTS_SUMMARY   = DECISIONS_DIR / "decision_events_summary.json"
PR_TIMING_AUDIT_JSON      = DECISIONS_DIR / "pr_timing_audit.json"
PR_TIMING_AUDIT_MD        = DECISIONS_DIR / "pr_timing_audit.md"

# Stage 3 — Infrastructure
ROUTES_CLEAN_PARQUET      = INFRASTRUCTURE_DIR / "routes_clean.parquet"
TRACKS_INVENTORY_PARQUET  = INFRASTRUCTURE_DIR / "tracks_inventory.parquet"
SIGNALS_INVENTORY_PARQUET = INFRASTRUCTURE_DIR / "signals_inventory.parquet"
AUXILIARY_PARQUET         = INFRASTRUCTURE_DIR / "auxiliary_connections.parquet"
INFRASTRUCTURE_GRAPH_JSON = INFRASTRUCTURE_DIR / "infrastructure_graph.json"

# Stage 4 — Static heterogeneous graph (4 node × 6 edge types)
NODE_TRACK_PARQUET   = STATIC_GRAPH_DIR / "nodes_track.parquet"
NODE_SIGNAL_PARQUET  = STATIC_GRAPH_DIR / "nodes_signal.parquet"
NODE_ROUTE_PARQUET   = STATIC_GRAPH_DIR / "nodes_route.parquet"
NODE_TRTS_PARQUET    = STATIC_GRAPH_DIR / "nodes_trts.parquet"

EDGE_PROTECTS_PARQUET    = STATIC_GRAPH_DIR / "edges_protects.parquet"
EDGE_CONNECTS_PARQUET    = STATIC_GRAPH_DIR / "edges_connects.parquet"
EDGE_TRAVERSES_PARQUET   = STATIC_GRAPH_DIR / "edges_traverses.parquet"
EDGE_STARTS_AT_PARQUET   = STATIC_GRAPH_DIR / "edges_starts_at.parquet"
EDGE_ENDS_AT_PARQUET     = STATIC_GRAPH_DIR / "edges_ends_at.parquet"
EDGE_SAME_SIGNAL_PARQUET = STATIC_GRAPH_DIR / "edges_same_signal.parquet"

STATIC_GRAPH_SUMMARY_JSON = STATIC_GRAPH_DIR / "static_graph_summary.json"
ASSET_INDEX_PARQUET       = STATIC_GRAPH_DIR / "asset_index.parquet"  # 672 assets

# Stage 5 — Event token stream
EVENT_STREAM_PARQUET = EVENT_STREAM_DIR / "event_tokens.parquet"
EVENT_TOKEN_K = 256

# Stage 6 — Pass assignment (NEW in v2 per spec 01 §17.2)
PASS_ASSIGNMENTS_PARQUET = PASSES_DIR / "pass_assignments.parquet"

# Stage 7 — Reward calibration
CALIBRATION_JSON              = REWARDS_DIR / "calibration.json"
CALIBRATION_HEADWAY_HIST_PNG  = REWARDS_DIR / "headway_distribution.png"
CALIBRATION_APPROACH_HIST_PNG = REWARDS_DIR / "approach_distance_distribution.png"
CALIBRATION_TIPLOC_HIST_PNG   = REWARDS_DIR / "tiploc_lag_distribution.png"
CALIBRATION_SUMMARY_MD        = REWARDS_DIR / "calibration_summary.md"

# Stage 8 — PR outcome labels
PR_OUTCOMES_PARQUET = REWARDS_DIR / "pr_outcomes.parquet"
PR_OUTCOMES_SUMMARY = REWARDS_DIR / "pr_outcomes_summary.json"

# Stage 9 + 10 — Per-decision features + final reward table
DECISION_REWARDS_PARQUET = REWARDS_DIR / "decision_rewards.parquet"
DECISION_REWARDS_SUMMARY = REWARDS_DIR / "decision_rewards_summary.json"

# TD parquet cache
TD_PARQUET        = CACHE_DIR / "td_data.parquet"
MOVEMENTS_PARQUET = CACHE_DIR / "movements.parquet"

# 🔴 Movements BST acquisition bug (found 2026-05-24): all Movements timestamps
# (actual/planned/gbtt) are shifted +1h for the 2023-04-04 .. 2023-07-31 collection
# runs (double-applied BST upstream; corrected for Aug+ runs). Confirmed via per-day
# decision↔Movements offset (= +58.6 min = normal −1.4 + 60, ONLY Apr-Jul) and by
# Movements' own daily rhythm shifting +1h there. Internal delay (actual−planned) is
# unaffected (both shift together); only the absolute clock is wrong → misaligns with
# TD decision times. FIX: subtract 1h from these timestamps for rows in the window.
# Bounds fall inside data gaps (3/17-4/3, 8/1-8/9) so they're exact. See data_io.
# correct_movements_bst + IMPLEMENTATION_LOG 2026-05-24 "fix #2".
MOVEMENTS_BST_FIX_START = "2023-03-17"   # inclusive; in the Mar/Apr data gap
MOVEMENTS_BST_FIX_END   = "2023-08-05"   # exclusive; in the Jul/Aug data gap
MOVEMENTS_BST_FIX_DELTA_H = -1           # hours to add to in-window timestamps

# v2 MDP outputs (per spec 02 — to be generated in Stage 2-3)
DECISION_POINTS_V2_PARQUET = DECISION_POINTS_DIR / "decision_points_v2.parquet"
SNAPSHOTS_V2_PARQUET       = SNAPSHOTS_DIR / "snapshots_v2.parquet"
SNAPSHOTS_V2_SUMMARY       = SNAPSHOTS_DIR / "snapshots_v2_summary.json"
NORMALIZATION_STATS_JSON   = SNAPSHOTS_DIR / "normalization_stats.json"
# Time-based train/val/test split (spec 04 §4.1) — pass_id → split, assigned by
# each episode's start time. Replaces the earlier md5(pass_id) hash split which
# leaked future data (spec 04 §4.1 + 教训 6). Built by 00_build_time_split.py.
PASS_SPLIT_PARQUET         = SNAPSHOTS_DIR / "pass_split.parquet"

# === Calibration constants (LOCKED per spec 01 §9 — empirical from 14-month data) ===
HEADWAY_PERCENTILE_FOR_HMIN = 5
APPROACH_PERCENTILE_LOW     = 50
APPROACH_PERCENTILE_HIGH    = 90
TIPLOC_LAG_PERCENTILE       = 99

# === Pass / approach trigger constants (LOCKED per spec 01 §8, spec 02 §2) ===
APPROACH_K_HOPS              = 2     # spec 02 §2.3 K_APPROACH
DECISION_LOOKAHEAD_SECONDS   = 30    # spec 02 §2.3 Δ_WAIT
PASS_LOOKUP_BUFFER_S         = 1800  # ±30 min TRUST id match buffer
PASS_FALLBACK_GAP_S          = 21600 # 6 h gap = new fallback pass
APPROACH_WINDOW_FORWARD_S    = 600   # PR within 10 min of approach = reactive
ALIGN_WINDOW_SECONDS         = 10    # legacy v1; kept for back-compat

# === Reward weights (LOCKED per spec 01 §12.2 — IRL Stage 2 may re-learn) ===
REWARD_WEIGHTS_DEFAULT = {
    "w_delay":      1.0,
    "w_throughput": 0.5,
    "w_headway":    1.0,
    "w_wait":       0.3,
}

# === MDP constants (LOCKED per spec 02) ===
DISCOUNT_GAMMA = 0.95     # spec 02 §5.4
SUBGRAPH_HOPS  = 3        # spec 02 §4.2
TIME_WINDOWS_MINUTES = (1, 5, 10, 15, 30)  # spec 02 §4.3
SCHEDULE_LOOKAHEAD_MIN = 15                # spec 02 §4.9
SCHEDULE_OUTLOOK_TOPK  = 5                 # spec 02 §4.9

# Platform id range. Spec 01 §17.5.4 originally locked 1-6, but real Derby
# data + user domain knowledge (2026-05-20) confirms platform 7 is the
# **pilot line** (north dep EC5487, south dep EC5484, TCs TECV/TECS).
# Expanded to 1-7 so schedule_outlook + leak_audit accept it.
MIN_PLATFORM_ID = 1
MAX_PLATFORM_ID = 7

# === Padding caps (LOCKED per spec 03 §2.1) ===
MAX_TRACKS_PADDED     = 60
MAX_SIGNALS_PADDED    = 15
MAX_ROUTES_PADDED     = 15
MAX_TRAINS_PADDED     = 8
MAX_CANDIDATES_PADDED = 14

# === Training constants (LOCKED per spec 04) ===
CQL_ALPHA      = 5.0
CQL_TARGET_TAU = 0.005
IQL_EXPECTILE_TAU = 0.7
IQL_AWR_BETA      = 3.0
SEEDS           = (42, 43, 44)
BATCH_SIZE      = 256
LR              = 3e-4
WEIGHT_DECAY    = 1e-4
WARMUP_STEPS    = 1000
GRAD_CLIP       = 1.0
PHASE_A_EPOCHS  = 5
PHASE_B_EPOCHS  = 15
PHASE_C_EPOCHS  = 20

# === Train/val/test split dates (LOCKED per spec 04 §4.1) ===
TRAIN_START = "2023-02-28"
TRAIN_END   = "2024-01-31"
VAL_START   = "2024-02-01"
VAL_END     = "2024-02-29"
TEST_START  = "2024-03-01"
TEST_END    = "2024-04-25"

# === XAI / Eval constants (LOCKED per spec 05) ===
L3_HORIZON_MIN  = 30   # spec 05 §9
L3_DELTA_THRESH = 0.5  # spec 05 §4.2 + §12.1 — divergent-improving threshold
L2_FAITHFULNESS_THRESH = 0.7  # spec 05 §12.2

# === Domain constants ===
DERBY_PREFIXES = ["DW", "TD", "DC", "EC", "DY"]

PREFIX_DESCRIPTION = {
    "DW": "Derby to Wichnor Junction (south corridor)",
    "TD": "Trent Junction to Derby (eastern approach + station)",
    "DC": "Derby to Chesterfield (north corridor)",
    "EC": "Etches Park to Chaddesden (depot / sidings)",
    "DY": "Duffield to north (re-controlled segment)",
}

HEADCODE_CLASS = {
    "0": "Light engine",
    "1": "Express passenger / fast",
    "2": "Stopping / semi-fast passenger",
    "3": "Parcels / postal",
    "4": "Container / freight (intermodal)",
    "5": "Empty coaching stock (ECS)",
    "6": "Heavy freight",
    "7": "Other (non-standard)",
    "8": "Other (non-standard)",
    "9": "High-speed / Channel Tunnel / VSTP",
}
HEADCODE_NON_STANDARD = "non_standard"

ROUTE_CLASS = {
    "M": "Main route",
    "C": "Call-on route (permissive working)",
    "S": "Shunt route",
    "W": "Warner route",
    "PS": "Proceed on Sight authority",
    "SP": "Shunt Position (Derby-specific; depot/sidings routes)",
}


# === Diagnostics ===

def describe() -> str:
    """Show all resolved paths and existence checks. Useful for sanity check."""
    paths = [
        ("PROJECT_ROOT",       PROJECT_ROOT,        None),
        ("DATA_DIR",           DATA_DIR,            None),
        ("REFERENCE_DIR",      REFERENCE_DIR,       None),
        ("DOMAIN_DIR",         DOMAIN_DIR,          None),
        ("OUTPUTS_DIR",        OUTPUTS_DIR,         None),
        ("TD_CSV",             TD_CSV,              "raw"),
        ("MOVEMENTS_CSV",      MOVEMENTS_CSV,       "raw"),
        ("ROUTE_TO_TC_CSV",    ROUTE_TO_TC_CSV,     "raw"),
        ("DERBY_INFO_CSV",     DERBY_INFO_CSV,      "reference"),
        ("DERBY_INFO_MAPPING", DERBY_INFO_MAPPING_CSV, "reference"),
        ("SOP_FILE",           SOP_FILE,            "reference"),
        ("PLATFORM_END_CSV",   PLATFORM_END_SIGNALS_CSV, "reference"),
        ("PLATFORM_TC_MAP",    PLATFORM_TC_MAP_CSV, "reference"),
        ("DERBY_PANEL_PNG",    DERBY_PANEL_PNG,     "reference"),
        ("TRAINING_PLAN",      TRAINING_PLAN_DOCX,  "domain"),
        ("DECISION_EVENTS",    DECISION_EVENTS_PARQUET, "output"),
        ("CALIBRATION_JSON",   CALIBRATION_JSON,    "output"),
        ("DECISION_REWARDS",   DECISION_REWARDS_PARQUET, "output"),
    ]
    lines = []
    for name, path, kind in paths:
        exists = "OK" if path.exists() else "MISSING"
        if kind is None:
            lines.append(f"{name:20s} = {path}")
        else:
            lines.append(f"{name:20s} = {path}  [{kind}]  {exists}")
    return "\n".join(lines)


def verify_paths_resolved() -> bool:
    """Hard check that all required input files exist. Raises if any missing."""
    required = [
        ("TD_CSV", TD_CSV),
        ("MOVEMENTS_CSV", MOVEMENTS_CSV),
        ("ROUTE_TO_TC_CSV", ROUTE_TO_TC_CSV),
        ("DERBY_INFO_CSV", DERBY_INFO_CSV),
        ("DERBY_INFO_MAPPING_CSV", DERBY_INFO_MAPPING_CSV),
        ("SOP_FILE", SOP_FILE),
        ("PLATFORM_END_SIGNALS_CSV", PLATFORM_END_SIGNALS_CSV),
        ("PLATFORM_TC_MAP_CSV", PLATFORM_TC_MAP_CSV),
    ]
    missing = [(name, str(path)) for name, path in required if not path.exists()]
    if missing:
        msg = "Missing required input files:\n" + "\n".join(
            f"  - {name}: {path}" for name, path in missing)
        raise FileNotFoundError(msg)
    return True

# (platform 1-7 expansion 2026-05-20)
